### PR TITLE
Final-ish version of ProgressMeter.  Needs addition of icon to match other API calls

### PR DESCRIPTION
**Pull request by MikeTheWatchGuy**
Removed the single-line create-and-update function from wxsimpleGUI.py.

My project includes a couple of other files.  I guess I shouldn't have uploaded them, but I kinda want them stored up here and maybe even make them available later, especially after I finish the code for lazyGUI / FlexForms.  I'll move them to another git when that happens.

### CODE REVIEW

**Comment by MikeTheWatchGuy** [comment]
Someday I hope to be good enough at Python to pass a lint checker and maybe get included in some open source project.   Gotta have dreams, right?  🙄

Was looking back to see "where it all started" and I see now that it was with you, on this project, that it all started.  I appreciate all the help and encouragement and advice and tutoring.  

Happy 2021!

**Comment by JorjMcKie** [comment]
Hi Mike,
happy 2021 to you too! And, as we all have been reminded by now: best of health!
How are things going - I am still using PySimpleGUI and I see it is flourishing, being further and further developed and used by so many others ...

Let's be realistic: wxsimpleGUI was never any more than two handful of GUI snippets - compared to it, PySimpleGUI plays in the champions' league.

**Comment by MikeTheWatchGuy** [comment]
Ah, the good ones are always modest.

Where PySimpleGUI has gone is one discussion....but not the discussion I was having.  I was talking about "Where it started".

Inspiration is just as important as perspiration.  It was your inspiration that led to PySimpleGUI.  I worked my ass off to get it to where it is currently, but that's not the important bit I was talking about.

Look at the names... wxsimpleGUI.... PySimpleGUI.

I changed 3 letters.  wxs became PyS.  The rest stayed the same.

I wouldn't have made PySimpleGUI without first seeing wxsimpleGUI.  Your influence, direct and indirect help, Python assistance, encouragement, ....., they all played a part too of course.

I'm piecing together a bit of the history and I'm able to trace right directly back to you and this project.  It's a very straight and obvious line and one I'll be sharing.  I was asked to be interviewed for a blog.  

> 1) Do you have an elevator pitch or tagline for PySimpleGUI?
> 2) Are there frameworks, libraries, or other software you drew inspiration from?
> 3) We all know the Zen of Python. What is the Zen of PySimpleGUI?
> 4) You study a lot of code the users of PySimpleGUI write. What do you learn from them?
> 5) What role do your project vision, the everyday usage, and the community feedback play in the evolution of PySimpleGUI?
> 6) What's the most surprising use of PySimpleGUI you've seen?

Line 2, where I "drew inspiration from".... that would be right here, from you.  Period.  It's also the first place on GitHub that I did anything.  

I came here to give you fair warning that you're going to get the blame.  Sorry mate.

PySimpleGUI is going pretty bonkers.  It's the account itself that trends like crazy.  Number 1 developer account for Python projects on Mon and Tues this week.  It's been doing this for the past year.  It's kinda nuts.  But it's also not surprising.  

This is the trending report I sometimes look at to see what GitHub is reporting as "trending", whatever that may even mean is a mystery.

https://github.com/trending/developers/python?since=daily

It was obvious once you and I worked on this project that there was a massive vacuum for making GUIs in Python.  You started filling it, I simply took it further.  "Anything worth doing's worth overdoing".  I'm good at overdoing.  Looks to me like you showed me where the opportunity was, the "opportunity ball" as it were, and I grabbed it and took off running.  

There have been some very very helpful people that made PySimpleGUI get to where it is now.  Sure, I wrote a ton of code, docs, etc, but there have been a number of critical people.  Jason Yang's support of the Issues has been a MASSIVE success.  He's literally been the face of PySimpleGUI for the past several months since he's managed the issues 100% while I'm off making a Udemy course.  nngogol wrote a lot of the docstrings and the tools that turn them into the online call reference and main docs.  They're a HUGE part of the package.  

So, yea, plenty of credit everywhere.  It sure ain't all me that deserves nor will get the credit.  A really talented young programmer, Tanay, has been working directly in the code.  He's the only other person besides nngogol that I trust with the code or have the bandwidth to trust with the code.

I hope you're ok with the "Let's be realistic" that a little more "realistic" than the highly simplified 1-line impact statement you made.  😉  Thanks for being one of the very positive voices I heard in my Python journey.  You're not going to be forgotten.

**Comment by MikeTheWatchGuy** [comment]
I too use PySimpleGUI for stuff on occasion...

Here's my "monitor monitor" that has quite a bit of control and monitoring widgets running all the time.

image

**Comment by MikeTheWatchGuy** [comment]
Oh, I see from the readme, that I also stole your import statement:

```python
import wxsimpleGUI as sg
```

Every PySimpleGUI program starts with

```python
import PySimpleGUI as sg
```

**Comment by JorjMcKie** [comment]
Hi Mike, ok I surrender and just accept your compliments.
A *big* thank you for this at least. I wasn’t aware it meant that much.
And good and satisfying to hear how well underway this package is nowadays.
Also great to see you have built up a real team caring about pysimplegui.

All the best to you!
Cheers, Jorj 

Von meinem iPhone gesendet

**Comment by MikeTheWatchGuy** [comment]
"Asking is just polite demanding".  I'm good at "too much" and will type a 200,000-word essay eventually if led in that direction. 
 It's perhaps better to just relent and agree.  

I thought maybe you understood all this that I wrote but realized last night that I never came out and told you how huge of an impact you have been.

It's funny too, that today PySimpleGUI isn't anywhere to be found in the trending GitHub Python projects.  I was at #1 Monday and Tuesday, honest. LOL....

It doesn't matter in the end though.  Trends are trends.  The big numbers don't mean so much when it comes to motivation.  It's the individual emails I get from users that have mattered.  It's those that have kept me going.  The simple "Thank you" emails are incredibly powerful in their impact.  Some of them have been really emotional and from the sender's heart.  I can tell that PySimpleGUI made a difference in that person's life, in a meaningful way.  In the big picture, it doesn't matter if it's 100 people that have that experience or 100,000, as long as someone is getting the benefits then it's worth it.

It seemed fitting to say something once I found where the inspiration and encouragement came from.

**Pull request closed without merging**
